### ISSUE TITLE
Content - Code Challenge - MockUp Creation

### ISSUE THREAD

**Issue by Chrissydrx** [SE2-WS23/documentation#10]
![image](https://github.com/SE2-WS23/documentation/assets/37250473/96e7c27b-2399-45bd-859a-facd50ba2e25)

**Comment by NicolasKmbr** [comment]
Change Components to match design system: https://www.figma.com/file/naq0V24YOBMXiEvp2vT0Eh/Material-UI-for-Figma-(and-MUI-X)-(Community)?type=design&node-id=6318-101112&mode=design&t=kBh09eRWtqLH6rFi-0
