### ISSUE TITLE
Content - Assessment - MockUp Creation

### ISSUE THREAD

**Issue by Chrissydrx** [SE2-WS23/documentation#14]
![image](https://github.com/SE2-WS23/documentation/assets/37250473/9a0fb6cd-5412-44bd-8273-54cb0910e3d4)

**Comment by NicolasKmbr** [comment]
Change Components to match design system: https://www.figma.com/file/naq0V24YOBMXiEvp2vT0Eh/Material-UI-for-Figma-(and-MUI-X)-(Community)?type=design&node-id=6318-101112&mode=design&t=kBh09eRWtqLH6rFi-0
