### ISSUE TITLE
Content - Quiz - MockUp Creation

### ISSUE THREAD

**Issue by j0world** [SE2-WS23/documentation#15]
<img width="786" alt="Screenshot 2023-10-26 at 14 59 46" src="https://github.com/SE2-WS23/documentation/assets/136974808/fe59a69e-d32f-4d48-b14e-fef552dced28">

**Comment by j0world** [comment]
<svg width="1280" height="832" viewBox="0 0 1280 832" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="1280" height="832" fill="white"/>
<rect x="306" y="283" width="696" height="459" rx="10" fill="#D9D9D9"/>
<rect x="1064" y="742" width="149" height="57" rx="10" fill="#D9D9D9"/>
<path d="M1117.85 771.125V779H1115.84V765.909H1117.78V767.955H1117.95C1118.26 767.29 1118.73 766.756 1119.35 766.352C1119.98 765.943 1120.78 765.739 1121.77 765.739C1122.66 765.739 1123.43 765.92 1124.1 766.284C1124.76 766.642 1125.28 767.188 1125.65 767.92C1126.02 768.648 1126.2 769.568 1126.2 770.682V779H1124.19V770.818C1124.19 769.79 1123.93 768.989 1123.39 768.415C1122.86 767.835 1122.13 767.545 1121.19 767.545C1120.55 767.545 1119.98 767.685 1119.47 767.963C1118.97 768.241 1118.58 768.648 1118.29 769.182C1118 769.716 1117.85 770.364 1117.85 771.125ZM1135.37 779.273C1134.11 779.273 1133.02 778.994 1132.1 778.438C1131.2 777.875 1130.49 777.091 1130 776.085C1129.51 775.074 1129.27 773.898 1129.27 772.557C1129.27 771.216 1129.51 770.034 1130 769.011C1130.49 767.983 1131.18 767.182 1132.06 766.608C1132.95 766.028 1133.98 765.739 1135.16 765.739C1135.85 765.739 1136.52 765.852 1137.18 766.08C1137.85 766.307 1138.45 766.676 1139 767.188C1139.54 767.693 1139.98 768.364 1140.3 769.199C1140.63 770.034 1140.79 771.062 1140.79 772.284V773.136H1130.7V771.398H1138.74C1138.74 770.659 1138.6 770 1138.3 769.42C1138.01 768.841 1137.6 768.384 1137.06 768.048C1136.52 767.713 1135.89 767.545 1135.16 767.545C1134.36 767.545 1133.67 767.744 1133.08 768.142C1132.5 768.534 1132.06 769.045 1131.75 769.676C1131.43 770.307 1131.28 770.983 1131.28 771.705V772.864C1131.28 773.852 1131.45 774.69 1131.79 775.378C1132.14 776.06 1132.62 776.58 1133.23 776.938C1133.84 777.29 1134.56 777.466 1135.37 777.466C1135.9 777.466 1136.37 777.392 1136.8 777.244C1137.23 777.091 1137.6 776.864 1137.92 776.562C1138.23 776.256 1138.47 775.875 1138.64 775.42L1140.58 775.966C1140.38 776.625 1140.04 777.205 1139.55 777.705C1139.07 778.199 1138.47 778.585 1137.76 778.864C1137.05 779.136 1136.25 779.273 1135.37 779.273ZM1145 765.909L1148.13 771.261L1151.27 765.909H1153.59L1149.36 772.455L1153.59 779H1151.27L1148.13 773.92L1145 779H1142.68L1146.84 772.455L1142.68 765.909H1145ZM1162.15 765.909V767.614H1155.37V765.909H1162.15ZM1157.34 762.773H1159.36V775.25C1159.36 775.818 1159.44 776.244 1159.6 776.528C1159.77 776.807 1159.99 776.994 1160.25 777.091C1160.52 777.182 1160.8 777.227 1161.09 777.227C1161.32 777.227 1161.5 777.216 1161.64 777.193C1161.78 777.165 1161.9 777.142 1161.98 777.125L1162.39 778.932C1162.25 778.983 1162.06 779.034 1161.82 779.085C1161.57 779.142 1161.26 779.17 1160.89 779.17C1160.32 779.17 1159.76 779.048 1159.22 778.804C1158.68 778.56 1158.23 778.188 1157.87 777.688C1157.52 777.188 1157.34 776.557 1157.34 775.795V762.773Z" fill="black"/>
<rect x="465" y="584" width="377" height="54" rx="15" fill="#AFAFAF"/>
<rect x="464.544" y="655.938" width="377.914" height="53.55" rx="15" fill="#AFAFAF"/>
<rect x="465" y="513" width="377" height="53" rx="15" fill="#AFAFAF"/>
<path d="M494.83 548H492.614L499.023 530.545H501.205L507.614 548H505.398L500.182 533.307H500.045L494.83 548ZM495.648 541.182H504.58V543.057H495.648V541.182ZM512.071 540.125V548H510.06V534.909H512.003V536.955H512.173C512.48 536.29 512.946 535.756 513.571 535.352C514.196 534.943 515.003 534.739 515.991 534.739C516.878 534.739 517.653 534.92 518.318 535.284C518.983 535.642 519.5 536.188 519.869 536.92C520.239 537.648 520.423 538.568 520.423 539.682V548H518.412V539.818C518.412 538.79 518.145 537.989 517.611 537.415C517.077 536.835 516.344 536.545 515.412 536.545C514.77 536.545 514.196 536.685 513.69 536.963C513.19 537.241 512.795 537.648 512.506 538.182C512.216 538.716 512.071 539.364 512.071 540.125ZM533.371 537.841L531.565 538.352C531.451 538.051 531.283 537.759 531.062 537.474C530.846 537.185 530.55 536.946 530.175 536.759C529.8 536.571 529.32 536.477 528.735 536.477C527.934 536.477 527.266 536.662 526.732 537.031C526.204 537.395 525.94 537.858 525.94 538.42C525.94 538.92 526.121 539.315 526.485 539.605C526.849 539.895 527.417 540.136 528.19 540.33L530.133 540.807C531.303 541.091 532.175 541.526 532.749 542.111C533.323 542.69 533.61 543.437 533.61 544.352C533.61 545.102 533.394 545.773 532.962 546.364C532.536 546.955 531.94 547.42 531.173 547.761C530.406 548.102 529.513 548.273 528.496 548.273C527.161 548.273 526.056 547.983 525.181 547.403C524.306 546.824 523.752 545.977 523.519 544.864L525.428 544.386C525.61 545.091 525.954 545.619 526.46 545.972C526.971 546.324 527.638 546.5 528.462 546.5C529.4 546.5 530.144 546.301 530.695 545.903C531.252 545.5 531.531 545.017 531.531 544.455C531.531 544 531.371 543.619 531.053 543.312C530.735 543 530.246 542.767 529.587 542.614L527.406 542.102C526.207 541.818 525.326 541.378 524.763 540.781C524.207 540.179 523.928 539.426 523.928 538.523C523.928 537.784 524.136 537.131 524.55 536.562C524.971 535.994 525.542 535.548 526.263 535.224C526.991 534.901 527.815 534.739 528.735 534.739C530.031 534.739 531.048 535.023 531.786 535.591C532.531 536.159 533.059 536.909 533.371 537.841ZM539.604 548L535.615 534.909H537.729L540.558 544.932H540.695L543.49 534.909H545.638L548.399 544.898H548.536L551.365 534.909H553.479L549.49 548H547.513L544.649 537.943H544.445L541.581 548H539.604ZM561.181 548.273C559.92 548.273 558.832 547.994 557.917 547.438C557.008 546.875 556.306 546.091 555.812 545.085C555.323 544.074 555.079 542.898 555.079 541.557C555.079 540.216 555.323 539.034 555.812 538.011C556.306 536.983 556.994 536.182 557.874 535.608C558.761 535.028 559.795 534.739 560.977 534.739C561.658 534.739 562.332 534.852 562.996 535.08C563.661 535.307 564.266 535.676 564.812 536.188C565.357 536.693 565.792 537.364 566.116 538.199C566.44 539.034 566.602 540.062 566.602 541.284V542.136H556.511V540.398H564.556C564.556 539.659 564.408 539 564.113 538.42C563.823 537.841 563.408 537.384 562.869 537.048C562.335 536.713 561.704 536.545 560.977 536.545C560.175 536.545 559.482 536.744 558.897 537.142C558.317 537.534 557.871 538.045 557.559 538.676C557.246 539.307 557.09 539.983 557.09 540.705V541.864C557.09 542.852 557.261 543.69 557.602 544.378C557.948 545.06 558.428 545.58 559.042 545.938C559.656 546.29 560.369 546.466 561.181 546.466C561.71 546.466 562.187 546.392 562.613 546.244C563.045 546.091 563.417 545.864 563.729 545.562C564.042 545.256 564.283 544.875 564.454 544.42L566.397 544.966C566.192 545.625 565.849 546.205 565.366 546.705C564.883 547.199 564.286 547.585 563.576 547.864C562.866 548.136 562.067 548.273 561.181 548.273ZM569.661 548V534.909H571.604V536.886H571.741C571.979 536.239 572.411 535.713 573.036 535.31C573.661 534.906 574.366 534.705 575.15 534.705C575.298 534.705 575.482 534.707 575.704 534.713C575.925 534.719 576.093 534.727 576.207 534.739V536.784C576.138 536.767 575.982 536.741 575.738 536.707C575.499 536.668 575.246 536.648 574.979 536.648C574.343 536.648 573.775 536.781 573.275 537.048C572.781 537.31 572.388 537.673 572.099 538.139C571.815 538.599 571.673 539.125 571.673 539.716V548H569.661ZM591.443 530.545V548H589.33V532.761H589.227L584.966 535.591V533.443L589.33 530.545H591.443Z" fill="black"/>
<path d="M494.83 620H492.614L499.023 602.545H501.205L507.614 620H505.398L500.182 605.307H500.045L494.83 620ZM495.648 613.182H504.58V615.057H495.648V613.182ZM512.071 612.125V620H510.06V606.909H512.003V608.955H512.173C512.48 608.29 512.946 607.756 513.571 607.352C514.196 606.943 515.003 606.739 515.991 606.739C516.878 606.739 517.653 606.92 518.318 607.284C518.983 607.642 519.5 608.188 519.869 608.92C520.239 609.648 520.423 610.568 520.423 611.682V620H518.412V611.818C518.412 610.79 518.145 609.989 517.611 609.415C517.077 608.835 516.344 608.545 515.412 608.545C514.77 608.545 514.196 608.685 513.69 608.963C513.19 609.241 512.795 609.648 512.506 610.182C512.216 610.716 512.071 611.364 512.071 612.125ZM533.371 609.841L531.565 610.352C531.451 610.051 531.283 609.759 531.062 609.474C530.846 609.185 530.55 608.946 530.175 608.759C529.8 608.571 529.32 608.477 528.735 608.477C527.934 608.477 527.266 608.662 526.732 609.031C526.204 609.395 525.94 609.858 525.94 610.42C525.94 610.92 526.121 611.315 526.485 611.605C526.849 611.895 527.417 612.136 528.19 612.33L530.133 612.807C531.303 613.091 532.175 613.526 532.749 614.111C533.323 614.69 533.61 615.437 533.61 616.352C533.61 617.102 533.394 617.773 532.962 618.364C532.536 618.955 531.94 619.42 531.173 619.761C530.406 620.102 529.513 620.273 528.496 620.273C527.161 620.273 526.056 619.983 525.181 619.403C524.306 618.824 523.752 617.977 523.519 616.864L525.428 616.386C525.61 617.091 525.954 617.619 526.46 617.972C526.971 618.324 527.638 618.5 528.462 618.5C529.4 618.5 530.144 618.301 530.695 617.903C531.252 617.5 531.531 617.017 531.531 616.455C531.531 616 531.371 615.619 531.053 615.312C530.735 615 530.246 614.767 529.587 614.614L527.406 614.102C526.207 613.818 525.326 613.378 524.763 612.781C524.207 612.179 523.928 611.426 523.928 610.523C523.928 609.784 524.136 609.131 524.55 608.562C524.971 607.994 525.542 607.548 526.263 607.224C526.991 606.901 527.815 606.739 528.735 606.739C530.031 606.739 531.048 607.023 531.786 607.591C532.531 608.159 533.059 608.909 533.371 609.841ZM539.604 620L535.615 606.909H537.729L540.558 616.932H540.695L543.49 606.909H545.638L548.399 616.898H548.536L551.365 606.909H553.479L549.49 620H547.513L544.649 609.943H544.445L541.581 620H539.604ZM561.181 620.273C559.92 620.273 558.832 619.994 557.917 619.438C557.008 618.875 556.306 618.091 555.812 617.085C555.323 616.074 555.079 614.898 555.079 613.557C555.079 612.216 555.323 611.034 555.812 610.011C556.306 608.983 556.994 608.182 557.874 607.608C558.761 607.028 559.795 606.739 560.977 606.739C561.658 606.739 562.332 606.852 562.996 607.08C563.661 607.307 564.266 607.676 564.812 608.188C565.357 608.693 565.792 609.364 566.116 610.199C566.44 611.034 566.602 612.062 566.602 613.284V614.136H556.511V612.398H564.556C564.556 611.659 564.408 611 564.113 610.42C563.823 609.841 563.408 609.384 562.869 609.048C562.335 608.713 561.704 608.545 560.977 608.545C560.175 608.545 559.482 608.744 558.897 609.142C558.317 609.534 557.871 610.045 557.559 610.676C557.246 611.307 557.09 611.983 557.09 612.705V613.864C557.09 614.852 557.261 615.69 557.602 616.378C557.948 617.06 558.428 617.58 559.042 617.938C559.656 618.29 560.369 618.466 561.181 618.466C561.71 618.466 562.187 618.392 562.613 618.244C563.045 618.091 563.417 617.864 563.729 617.562C564.042 617.256 564.283 616.875 564.454 616.42L566.397 616.966C566.192 617.625 565.849 618.205 565.366 618.705C564.883 619.199 564.286 619.585 563.576 619.864C562.866 620.136 562.067 620.273 561.181 620.273ZM569.661 620V606.909H571.604V608.886H571.741C571.979 608.239 572.411 607.713 573.036 607.31C573.661 606.906 574.366 606.705 575.15 606.705C575.298 606.705 575.482 606.707 575.704 606.713C575.925 606.719 576.093 606.727 576.207 606.739V608.784C576.138 608.767 575.982 608.741 575.738 608.707C575.499 608.668 575.246 608.648 574.979 608.648C574.343 608.648 573.775 608.781 573.275 609.048C572.781 609.31 572.388 609.673 572.099 610.139C571.815 610.599 571.673 611.125 571.673 611.716V620H569.661ZM585.307 620V618.466L591.068 612.159C591.744 611.42 592.301 610.778 592.739 610.233C593.176 609.682 593.5 609.165 593.71 608.682C593.926 608.193 594.034 607.682 594.034 607.148C594.034 606.534 593.886 606.003 593.591 605.554C593.301 605.105 592.903 604.759 592.398 604.514C591.892 604.27 591.324 604.148 590.693 604.148C590.023 604.148 589.438 604.287 588.938 604.565C588.443 604.838 588.06 605.222 587.787 605.716C587.52 606.21 587.386 606.79 587.386 607.455H585.375C585.375 606.432 585.611 605.534 586.082 604.761C586.554 603.989 587.196 603.386 588.009 602.955C588.827 602.523 589.744 602.307 590.761 602.307C591.784 602.307 592.69 602.523 593.48 602.955C594.27 603.386 594.889 603.969 595.338 604.702C595.787 605.435 596.011 606.25 596.011 607.148C596.011 607.79 595.895 608.418 595.662 609.031C595.435 609.639 595.037 610.318 594.469 611.068C593.906 611.812 593.125 612.722 592.125 613.795L588.205 617.989V618.125H596.318V620H585.307Z" fill="black"/>
<path d="M494.83 692H492.614L499.023 674.545H501.205L507.614 692H505.398L500.182 677.307H500.045L494.83 692ZM495.648 685.182H504.58V687.057H495.648V685.182ZM512.071 684.125V692H510.06V678.909H512.003V680.955H512.173C512.48 680.29 512.946 679.756 513.571 679.352C514.196 678.943 515.003 678.739 515.991 678.739C516.878 678.739 517.653 678.92 518.318 679.284C518.983 679.642 519.5 680.188 519.869 680.92C520.239 681.648 520.423 682.568 520.423 683.682V692H518.412V683.818C518.412 682.79 518.145 681.989 517.611 681.415C517.077 680.835 516.344 680.545 515.412 680.545C514.77 680.545 514.196 680.685 513.69 680.963C513.19 681.241 512.795 681.648 512.506 682.182C512.216 682.716 512.071 683.364 512.071 684.125ZM533.371 681.841L531.565 682.352C531.451 682.051 531.283 681.759 531.062 681.474C530.846 681.185 530.55 680.946 530.175 680.759C529.8 680.571 529.32 680.477 528.735 680.477C527.934 680.477 527.266 680.662 526.732 681.031C526.204 681.395 525.94 681.858 525.94 682.42C525.94 682.92 526.121 683.315 526.485 683.605C526.849 683.895 527.417 684.136 528.19 684.33L530.133 684.807C531.303 685.091 532.175 685.526 532.749 686.111C533.323 686.69 533.61 687.437 533.61 688.352C533.61 689.102 533.394 689.773 532.962 690.364C532.536 690.955 531.94 691.42 531.173 691.761C530.406 692.102 529.513 692.273 528.496 692.273C527.161 692.273 526.056 691.983 525.181 691.403C524.306 690.824 523.752 689.977 523.519 688.864L525.428 688.386C525.61 689.091 525.954 689.619 526.46 689.972C526.971 690.324 527.638 690.5 528.462 690.5C529.4 690.5 530.144 690.301 530.695 689.903C531.252 689.5 531.531 689.017 531.531 688.455C531.531 688 531.371 687.619 531.053 687.312C530.735 687 530.246 686.767 529.587 686.614L527.406 686.102C526.207 685.818 525.326 685.378 524.763 684.781C524.207 684.179 523.928 683.426 523.928 682.523C523.928 681.784 524.136 681.131 524.55 680.562C524.971 679.994 525.542 679.548 526.263 679.224C526.991 678.901 527.815 678.739 528.735 678.739C530.031 678.739 531.048 679.023 531.786 679.591C532.531 680.159 533.059 680.909 533.371 681.841ZM539.604 692L535.615 678.909H537.729L540.558 688.932H540.695L543.49 678.909H545.638L548.399 688.898H548.536L551.365 678.909H553.479L549.49 692H547.513L544.649 681.943H544.445L541.581 692H539.604ZM561.181 692.273C559.92 692.273 558.832 691.994 557.917 691.438C557.008 690.875 556.306 690.091 555.812 689.085C555.323 688.074 555.079 686.898 555.079 685.557C555.079 684.216 555.323 683.034 555.812 682.011C556.306 680.983 556.994 680.182 557.874 679.608C558.761 679.028 559.795 678.739 560.977 678.739C561.658 678.739 562.332 678.852 562.996 679.08C563.661 679.307 564.266 679.676 564.812 680.188C565.357 680.693 565.792 681.364 566.116 682.199C566.44 683.034 566.602 684.062 566.602 685.284V686.136H556.511V684.398H564.556C564.556 683.659 564.408 683 564.113 682.42C563.823 681.841 563.408 681.384 562.869 681.048C562.335 680.713 561.704 680.545 560.977 680.545C560.175 680.545 559.482 680.744 558.897 681.142C558.317 681.534 557.871 682.045 557.559 682.676C557.246 683.307 557.09 683.983 557.09 684.705V685.864C557.09 686.852 557.261 687.69 557.602 688.378C557.948 689.06 558.428 689.58 559.042 689.938C559.656 690.29 560.369 690.466 561.181 690.466C561.71 690.466 562.187 690.392 562.613 690.244C563.045 690.091 563.417 689.864 563.729 689.562C564.042 689.256 564.283 688.875 564.454 688.42L566.397 688.966C566.192 689.625 565.849 690.205 565.366 690.705C564.883 691.199 564.286 691.585 563.576 691.864C562.866 692.136 562.067 692.273 561.181 692.273ZM569.661 692V678.909H571.604V680.886H571.741C571.979 680.239 572.411 679.713 573.036 679.31C573.661 678.906 574.366 678.705 575.15 678.705C575.298 678.705 575.482 678.707 575.704 678.713C575.925 678.719 576.093 678.727 576.207 678.739V680.784C576.138 680.767 575.982 680.741 575.738 680.707C575.499 680.668 575.246 680.648 574.979 680.648C574.343 680.648 573.775 680.781 573.275 681.048C572.781 681.31 572.388 681.673 572.099 682.139C571.815 682.599 571.673 683.125 571.673 683.716V692H569.661ZM591.205 692.239C590.08 692.239 589.077 692.045 588.196 691.659C587.321 691.273 586.625 690.736 586.108 690.048C585.597 689.355 585.318 688.551 585.273 687.636H587.42C587.466 688.199 587.659 688.685 588 689.094C588.341 689.497 588.787 689.81 589.338 690.031C589.889 690.253 590.5 690.364 591.17 690.364C591.92 690.364 592.585 690.233 593.165 689.972C593.744 689.71 594.199 689.347 594.528 688.881C594.858 688.415 595.023 687.875 595.023 687.261C595.023 686.619 594.864 686.054 594.545 685.565C594.227 685.071 593.761 684.685 593.148 684.406C592.534 684.128 591.784 683.989 590.898 683.989H589.5V682.114H590.898C591.591 682.114 592.199 681.989 592.722 681.739C593.25 681.489 593.662 681.136 593.957 680.682C594.259 680.227 594.409 679.693 594.409 679.08C594.409 678.489 594.278 677.974 594.017 677.537C593.756 677.099 593.386 676.759 592.909 676.514C592.438 676.27 591.881 676.148 591.239 676.148C590.636 676.148 590.068 676.259 589.534 676.48C589.006 676.696 588.574 677.011 588.239 677.426C587.903 677.835 587.722 678.33 587.693 678.909H585.648C585.682 677.994 585.957 677.193 586.474 676.506C586.991 675.812 587.668 675.273 588.503 674.886C589.344 674.5 590.267 674.307 591.273 674.307C592.352 674.307 593.278 674.526 594.051 674.963C594.824 675.395 595.418 675.966 595.832 676.676C596.247 677.386 596.455 678.153 596.455 678.977C596.455 679.96 596.196 680.798 595.679 681.491C595.168 682.185 594.472 682.665 593.591 682.932V683.068C594.693 683.25 595.554 683.719 596.173 684.474C596.793 685.224 597.102 686.153 597.102 687.261C597.102 688.21 596.844 689.062 596.327 689.818C595.815 690.568 595.116 691.159 594.23 691.591C593.344 692.023 592.335 692.239 591.205 692.239Z" fill="black"/>
<rect x="168" y="214" width="971" height="17" rx="8.5" fill="#D9D9D9"/>
<rect x="168" y="214" width="396" height="17" rx="8.5" fill="#097500"/>
<path d="M568.909 401.091H573.545L577.432 406.205L578.455 407.568L584.25 415.273H579.614L575.795 410.159L574.841 408.864L568.909 401.091ZM585.682 394.545C585.682 398.227 585.017 401.409 583.688 404.091C582.358 406.773 580.534 408.841 578.216 410.295C575.898 411.75 573.25 412.477 570.273 412.477C567.295 412.477 564.648 411.75 562.33 410.295C560.011 408.841 558.188 406.773 556.858 404.091C555.528 401.409 554.864 398.227 554.864 394.545C554.864 390.864 555.528 387.682 556.858 385C558.188 382.318 560.011 380.25 562.33 378.795C564.648 377.341 567.295 376.614 570.273 376.614C573.25 376.614 575.898 377.341 578.216 378.795C580.534 380.25 582.358 382.318 583.688 385C585.017 387.682 585.682 390.864 585.682 394.545ZM581.591 394.545C581.591 391.523 581.085 388.972 580.074 386.892C579.074 384.812 577.716 383.239 576 382.17C574.295 381.102 572.386 380.568 570.273 380.568C568.159 380.568 566.244 381.102 564.528 382.17C562.824 383.239 561.466 384.812 560.455 386.892C559.455 388.972 558.955 391.523 558.955 394.545C558.955 397.568 559.455 400.119 560.455 402.199C561.466 404.278 562.824 405.852 564.528 406.92C566.244 407.989 568.159 408.523 570.273 408.523C572.386 408.523 574.295 407.989 576 406.92C577.716 405.852 579.074 404.278 580.074 402.199C581.085 400.119 581.591 397.568 581.591 394.545ZM608.744 401.295V385.818H612.767V412H608.744V407.568H608.472C607.858 408.898 606.903 410.028 605.608 410.96C604.313 411.881 602.676 412.341 600.699 412.341C599.062 412.341 597.608 411.983 596.335 411.267C595.063 410.54 594.063 409.449 593.335 407.994C592.608 406.528 592.244 404.682 592.244 402.455V385.818H596.267V402.182C596.267 404.091 596.801 405.614 597.869 406.75C598.949 407.886 600.324 408.455 601.994 408.455C602.994 408.455 604.011 408.199 605.045 407.688C606.091 407.176 606.966 406.392 607.67 405.335C608.386 404.278 608.744 402.932 608.744 401.295ZM631.112 412.545C628.589 412.545 626.413 411.989 624.584 410.875C622.766 409.75 621.362 408.182 620.374 406.17C619.396 404.148 618.908 401.795 618.908 399.114C618.908 396.432 619.396 394.068 620.374 392.023C621.362 389.966 622.737 388.364 624.499 387.216C626.271 386.057 628.339 385.477 630.703 385.477C632.067 385.477 633.413 385.705 634.743 386.159C636.072 386.614 637.283 387.352 638.374 388.375C639.464 389.386 640.334 390.727 640.982 392.398C641.629 394.068 641.953 396.125 641.953 398.568V400.273H621.771V396.795H637.862C637.862 395.318 637.567 394 636.976 392.841C636.396 391.682 635.567 390.767 634.487 390.097C633.419 389.426 632.158 389.091 630.703 389.091C629.101 389.091 627.714 389.489 626.544 390.284C625.385 391.068 624.493 392.091 623.868 393.352C623.243 394.614 622.93 395.966 622.93 397.409V399.727C622.93 401.705 623.271 403.381 623.953 404.756C624.646 406.119 625.607 407.159 626.834 407.875C628.061 408.58 629.487 408.932 631.112 408.932C632.169 408.932 633.124 408.784 633.976 408.489C634.839 408.182 635.584 407.727 636.209 407.125C636.834 406.511 637.317 405.75 637.658 404.841L641.544 405.932C641.135 407.25 640.447 408.409 639.482 409.409C638.516 410.398 637.322 411.17 635.902 411.727C634.482 412.273 632.885 412.545 631.112 412.545ZM666.618 391.682L663.004 392.705C662.777 392.102 662.442 391.517 661.999 390.949C661.567 390.369 660.976 389.892 660.226 389.517C659.476 389.142 658.516 388.955 657.345 388.955C655.743 388.955 654.408 389.324 653.339 390.062C652.283 390.79 651.754 391.716 651.754 392.841C651.754 393.841 652.118 394.631 652.845 395.21C653.572 395.79 654.709 396.273 656.254 396.659L660.141 397.614C662.482 398.182 664.226 399.051 665.374 400.222C666.521 401.381 667.095 402.875 667.095 404.705C667.095 406.205 666.663 407.545 665.8 408.727C664.947 409.909 663.754 410.841 662.22 411.523C660.686 412.205 658.902 412.545 656.868 412.545C654.197 412.545 651.987 411.966 650.237 410.807C648.487 409.648 647.379 407.955 646.913 405.727L650.732 404.773C651.095 406.182 651.783 407.239 652.794 407.943C653.817 408.648 655.152 409 656.8 409C658.675 409 660.163 408.602 661.266 407.807C662.379 407 662.936 406.034 662.936 404.909C662.936 404 662.618 403.239 661.982 402.625C661.345 402 660.368 401.534 659.05 401.227L654.686 400.205C652.288 399.636 650.527 398.756 649.402 397.562C648.288 396.358 647.732 394.852 647.732 393.045C647.732 391.568 648.146 390.261 648.976 389.125C649.817 387.989 650.959 387.097 652.402 386.449C653.857 385.801 655.504 385.477 657.345 385.477C659.936 385.477 661.97 386.045 663.447 387.182C664.936 388.318 665.993 389.818 666.618 391.682ZM684.537 385.818V389.227H670.969V385.818H684.537ZM674.923 379.545H678.946V404.5C678.946 405.636 679.111 406.489 679.44 407.057C679.781 407.614 680.213 407.989 680.736 408.182C681.27 408.364 681.832 408.455 682.423 408.455C682.866 408.455 683.23 408.432 683.514 408.386C683.798 408.33 684.026 408.284 684.196 408.25L685.014 411.864C684.741 411.966 684.361 412.068 683.872 412.17C683.384 412.284 682.764 412.341 682.014 412.341C680.878 412.341 679.764 412.097 678.673 411.608C677.594 411.119 676.696 410.375 675.98 409.375C675.276 408.375 674.923 407.114 674.923 405.591V379.545ZM690.588 412V385.818H694.611V412H690.588ZM692.634 381.455C691.849 381.455 691.173 381.188 690.605 380.653C690.048 380.119 689.77 379.477 689.77 378.727C689.77 377.977 690.048 377.335 690.605 376.801C691.173 376.267 691.849 376 692.634 376C693.418 376 694.088 376.267 694.645 376.801C695.213 377.335 695.497 377.977 695.497 378.727C695.497 379.477 695.213 380.119 694.645 380.653C694.088 381.188 693.418 381.455 692.634 381.455ZM712.615 412.545C710.251 412.545 708.178 411.983 706.393 410.858C704.621 409.733 703.234 408.159 702.234 406.136C701.246 404.114 700.751 401.75 700.751 399.045C700.751 396.318 701.246 393.937 702.234 391.903C703.234 389.869 704.621 388.29 706.393 387.165C708.178 386.04 710.251 385.477 712.615 385.477C714.979 385.477 717.047 386.04 718.82 387.165C720.604 388.29 721.99 389.869 722.979 391.903C723.979 393.937 724.479 396.318 724.479 399.045C724.479 401.75 723.979 404.114 722.979 406.136C721.99 408.159 720.604 409.733 718.82 410.858C717.047 411.983 714.979 412.545 712.615 412.545ZM712.615 408.932C714.411 408.932 715.888 408.472 717.047 407.551C718.206 406.631 719.064 405.42 719.621 403.92C720.178 402.42 720.456 400.795 720.456 399.045C720.456 397.295 720.178 395.665 719.621 394.153C719.064 392.642 718.206 391.42 717.047 390.489C715.888 389.557 714.411 389.091 712.615 389.091C710.82 389.091 709.342 389.557 708.183 390.489C707.024 391.42 706.166 392.642 705.609 394.153C705.053 395.665 704.774 397.295 704.774 399.045C704.774 400.795 705.053 402.42 705.609 403.92C706.166 405.42 707.024 406.631 708.183 407.551C709.342 408.472 710.82 408.932 712.615 408.932ZM734.642 396.25V412H730.619V385.818H734.506V389.909H734.847C735.46 388.58 736.392 387.511 737.642 386.705C738.892 385.886 740.506 385.477 742.483 385.477C744.256 385.477 745.807 385.841 747.136 386.568C748.466 387.284 749.5 388.375 750.239 389.841C750.977 391.295 751.347 393.136 751.347 395.364V412H747.324V395.636C747.324 393.58 746.79 391.977 745.722 390.83C744.653 389.67 743.188 389.091 741.324 389.091C740.04 389.091 738.892 389.369 737.881 389.926C736.881 390.483 736.091 391.295 735.511 392.364C734.932 393.432 734.642 394.727 734.642 396.25Z" fill="black"/>
</svg>

**Comment by j0world** [comment]
![image](https://github.com/SE2-WS23/documentation/assets/136974808/19c25382-190e-4fdb-9217-15320bab84d4)

**Comment by j0world** [comment]
![image](https://github.com/SE2-WS23/documentation/assets/136974808/127fe066-40b7-4f4f-a440-8f4032f5d57c)

**Comment by j0world** [comment]
<img width="787" alt="Screenshot 2023-10-26 at 14 58 07" src="https://github.com/SE2-WS23/documentation/assets/136974808/1bfbb7f5-76ac-4a61-a7c7-3c8c76304d1a">

**Comment by Arkcorner** [comment]
Change the Progressbar and rename the component

**Comment by j0world** [comment]
I changed things now :)
