### ISSUE TITLE
Content -Job Profile Skills Requriements- MockUp Creation

### ISSUE THREAD

**Issue by 11Meru11** [SE2-WS23/documentation#18]
Includes Job profile Step 2

**Comment by 11Meru11** [comment]
![grafik](https://github.com/SE2-WS23/documentation/assets/137390054/71247d31-1e9f-4a71-913e-c6e8e9a7612a)

**Comment by NicolasKmbr** [comment]
Please Change rectangles to our Library components as agreed on [https://www.figma.com/file/naq0V24YOBMXiEvp2vT0Eh/Material-UI-for-Figma-(and-MUI-X)-(Community)?type=design&node-id=6318-101112&mode=design&t=kBh09eRWtqLH6rFi-0](url)
