### ISSUE TITLE
Company employees - mockup creation

### ISSUE THREAD

**Issue by bishop6232** [SE2-WS23/documentation#22]
As an admin I would like to have an overview of all the employees and also modify it
![image](https://github.com/SE2-WS23/documentation/assets/104029083/096540d5-71eb-434e-b4fb-8059eb0ae334)

**Comment by NicolasKmbr** [comment]
Change Components to match design system: https://www.figma.com/file/naq0V24YOBMXiEvp2vT0Eh/Material-UI-for-Figma-(and-MUI-X)-(Community)?type=design&node-id=6318-101112&mode=design&t=kBh09eRWtqLH6rFi-0
