### ISSUE TITLE
Dashboard - MockUp Creation

### ISSUE THREAD

**Issue by WLueheCaSE** [SE2-WS23/documentation#25]
As an admin I would like to have a Dashboard to go to the Company Trainings, Company Employees and the Job Profiles
![image](https://github.com/SE2-WS23/documentation/assets/49426794/f37f882b-f3e8-4fc5-8517-75b6326dea4d)

**Comment by NicolasKmbr** [comment]
Change Components to match design system: https://www.figma.com/file/naq0V24YOBMXiEvp2vT0Eh/Material-UI-for-Figma-(and-MUI-X)-(Community)?type=design&node-id=6318-101112&mode=design&t=kBh09eRWtqLH6rFi-0
