### ISSUE TITLE
Content - Company Course Management - Mockup Creation

### ISSUE THREAD

**Issue by Ara-Ara-ASid-kun** [SE2-WS23/documentation#28]

**Comment by mohammed-abujarour** [comment]
@Ara-Ara-ASid-kun : Please add a screenshot of the wireframe

**Comment by Ara-Ara-ASid-kun** [comment]
![Company Course Management - Course](https://github.com/SE2-WS23/documentation/assets/136272095/90b6465d-fa32-4f86-9274-0d961bf9047a)

**Comment by NicolasKmbr** [comment]
Change components to align with our design system: https://www.figma.com/file/naq0V24YOBMXiEvp2vT0Eh/Material-UI-for-Figma-(and-MUI-X)-(Community)?type=design&node-id=6318-101112&mode=design&t=kBh09eRWtqLH6rFi-0
