### ISSUE TITLE
Create the front-end for Job profile describe the jobs

### ISSUE THREAD

**Issue by 11Meru11** [SE2-WS23/documentation#57]
![Job profile describe the jobs](https://github.com/SE2-WS23/documentation/assets/137390054/38fd6e8e-c6f7-463b-8fef-4a9806108875)

**Comment by 11Meru11** [comment]
hi i created the toggle button in a grid layout and its changing on activation. timewise because tomorrow came something in between im not able to make the toggle appear based on a constant for example the skills the company requires. if i can continue monday then i should be able to complete it but if it should be done till monday then i need someone to complete it
[JobProfileHilfe.zip](https://github.com/SE2-WS23/documentation/files/13400753/JobProfileHilfe.zip)

**Comment by julix14** [comment]
Moved to "in Progress" because currently no PR open

**Comment by 11Meru11** [comment]
Hi I'm struggling a lot with passing the state to the component and I don't think I'm gonna finish this page this week without help ^^

**Comment by julix14** [comment]
I take over this task
