### ISSUE TITLE
Create the Front-End for Company Employees/Employee Overview

### ISSUE THREAD

**Issue by WLueheCaSE** [SE2-WS23/documentation#60]
![Image](https://github.com/SE2-WS23/documentation/assets/135735235/189d3f6c-e390-4c90-a90a-83a3d9e0e393)

![Image](https://github.com/SE2-WS23/documentation/assets/135735235/7a3840d5-e041-43a4-b3c5-ecb30bc38916)

**Comment by julix14** [comment]
Please write this the next time in the Teams Channel, so others get notified about this circumstances @WLueheCaSE
