### ISSUE TITLE
Decide the Design System

### ISSUE THREAD

**Issue by Arkcorner** [SE2-WS23/documentation#8]
for example google material design
Example Framework:
https://m3.material.io/

**Comment by Chrissydrx** [comment]
More examples:
- https://developer.apple.com/design/?ref=designerup.co
- https://fluent2.microsoft.design

**Comment by Chrissydrx** [comment]
We would recommend to use the Material UI Library (It is already an implemented version of the material 2 guidelines with small adjustments). It has a decent Figma Plugin. The only tradeoff is that we cannot change the color scheme in our Figma and it's hard to change the visual style of the components in general. So, our Figma will not be a single point of truth, but it should be enough to create a coherent design.
MUI delivers already a complete React Library, so we recommend using it.
We also discussed about other Design Systems (Fluent2, Material3 and Apple Design System), but all of them have a big tradeoff (e.g. not complete libraries, no Figma Plugin).

**Comment by julix14** [comment]
[Documentation for MUI for Figma](https://mui-org.notion.site/MUI-for-Figma-docs-4eb22360388047a9a31fc19d300a285e#3d86a84cb9d3419ba93638c1147610dc)

[Material UI for Figma](https://www.figma.com/community/file/912837788133317724/material-ui-for-figma-and-mui-x)

[Material UI](https://mui.com/)

**Comment by mohammed-abujarour** [comment]
Approved by everyone
