### ISSUE TITLE
Deciding the Color theme 

### ISSUE THREAD

**Issue by Arkcorner** [SE2-WS23/documentation#9]

**Comment by Arkcorner** [comment]
We are using the Blue 800 as the Main colour tone for our website. The Colour palete can be found under this: https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors  link when you scrool down to the bottom.

**Comment by Markus799** [comment]
HEX: #1565C0

**Comment by mohammed-abujarour** [comment]
https://studywebdevelopment.com/web-design-tips.html#colors
